//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2024 January 16 09:27:27 UTC
// </auto-generated>
//---------------------------------------------------------

internal static class AssemblyInfo
{
  public const string ProductVersion = "2.0.1";
  public const string Copyright = "Copyright (c) 1997-2021 Robert McNeel and Associates\r\nCopyright (c) 2023 Grid Protection Alliance, Inc.";
}
