# This is a reusable workflow to build a .NET project or solution
name: .NET Build

on:
  # Called from another workflow passing input values
  workflow_call:
    inputs:
      run-name:
        description: A name for the run
        type: string
        default: ""
      runs-on:
        description: The runner type to use
        type: string
        default: ubuntu-latest
      project-folder:
        description: Folder containing the solution
        type: string
        default: .

  # Triggering manually
  workflow_dispatch:
     inputs:
      run-name:
        description: A name for the run
        type: string
        required: true
      runs-on:
        description: The runner type to use
        type: choice
        options:
        - ubuntu-latest
        - windows-latest
        default: ubuntu-latest
      project-folder:
        description: Folder containing the solution
        type: string
        default: .

run-name: ${{ inputs.run-name }}

jobs:

  dotnetbuild:
    name: Build .NET
    runs-on: ${{ inputs.runs-on }}
    env:
      BUILD_CONFIGURATION: Release
      ARTIFACT_PATH: ${{ github.workspace }}/local

    # Set the default working directory
    defaults:
      run:
        working-directory: ${{ inputs.project-folder }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create artifacts folder
        run: mkdir ${{ env.ARTIFACT_PATH }}

      - name: Restore build dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c ${{ env.BUILD_CONFIGURATION }}

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Build-Artifacts
      #     path: ${{ env.ARTIFACT_PATH }}
      #     retention-days: 5

