# This workflow is triggered when a pull request is merged and closed
name: ♾️ Pull Request Merged

on:
  pull_request:
    types: [ "closed" ]
    branches: [ "main" ]

jobs:
  Merged:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/build.yml

