# This workflow is triggered when a release is published
name: 📦 Upload Packages

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      run-name:
        description: A name for the run
        type: string
        required: true
      nuget-push:
        description: Push to NuGet
        type: boolean
        default: false

run-name: ${{ inputs.run-name }}
env:
  BUILD_CONFIGURATION: Release
  ARTIFACT_PATH: ${{ github.workspace }}/local
  nuget-push: ${{ github.event.release != null || inputs.nuget-push }}

jobs:
  upload:
    name: Packages Upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create artifacts folder
        run: mkdir ${{ env.ARTIFACT_PATH }}

      - name: Restore dependencies
        run: dotnet restore /property:Configuration=${{ env.BUILD_CONFIGURATION }}

      - name: .NET build
        run: dotnet build --no-restore -c ${{ env.BUILD_CONFIGURATION }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NuGetPackages-Local
          path: ${{ env.ARTIFACT_PATH }}
          retention-days: 5

      - name: NuGet push
        if: env.nuget-push == 'true'
        env:
          NUGET_URL: "https://api.nuget.org/v3/index.json"
        shell: pwsh
        run: |
          foreach($file in (Get-ChildItem "${{env.ARTIFACT_PATH}}" -Recurse -Include *.nupkg))
          { dotnet nuget push $file -k "${{secrets.NUGET_AUTH_TOKEN}}" -s "${{env.NUGET_URL}}" --skip-duplicate }
