# Uploads the release packages to NuGet
name: 📦 Upload to NuGet

on:
  release:
    types: [published]
    branches:
      - main
    inputs:
      run-name:
        description: A name for the run
        type: string
        default: ""

  workflow_dispatch:
    inputs:
      run-name:
        description: A name for the run
        type: string
        required: true

run-name: ${{ inputs.run-name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIGURATION: Release
      ARTIFACT_PATH: ${{ github.workspace }}/local

    steps:
      - uses: actions/checkout@v4

      - name: Create artifacts folder
        run: mkdir ${{ env.ARTIFACT_PATH }}

      - name: .NET restore
        run: dotnet restore

      - name: .NET build
        run: dotnet build --no-restore -c ${{ env.BUILD_CONFIGURATION }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NuGet-Local
          path: ${{ env.ARTIFACT_PATH }}
          retention-days: 5

      - name: NuGet push
        env:
          NUGET_URL: "https://api.nuget.org/v3/index.json"
        shell: pwsh
        run: |
          foreach($file in (Get-ChildItem "${{env.ARTIFACT_PATH}}" -Recurse -Include *.nupkg))
          { dotnet nuget push $file -k "${{secrets.NUGET_AUTH_TOKEN}}" -s "${{env.NUGET_URL}}" --skip-duplicate }
